sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jskinner9999/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jskinner9999/react-test npm test -- --coverage 

after_success:
  - docker build -t jskinner9999/multi-client ./client
  - docker build -t jskinner9999/multi-nginx ./nginx
  - docker build -t jskinner9999/multi-server ./server
  - docker build -t jskinner9999/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jskinner9999/multi-client
  - docker push jskinner9999/multi-nginx
  - docker push jskinner9999/multi-server
  - docker push jskinner9999/multi-worker
